### PR TITLE
Add Travis build

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by kquick** [comment]
Hi @gliptak ,

Thanks for the submission.  Was there an issue you ran into that this travis configuration reveals?  Our existing CI testing does not show any issues with this package and I'm curious to know if the existing CI has missed something.

**Comment by gliptak** [comment]
@kquick I noted this fail https://travis-ci.org/GaloisInc/abcBridge/jobs/598325086 , hence adding the Travis build here. Looks like it was corrected since ...

Is the existing build (log) you refer to publicly accessible?

**Comment by kquick** [comment]
Yeah, that Travis build is 2 months old.  We've been having some reliability issues with our Travis builds, so we have been working with an internal CI builder instance.  Unfortunately, that internal builder is not presently visible externally, although we are hoping to change that.

Your contribution is appreciated, but would it be OK with you if we don't merge this until we get better resolution on our CI plans?

**Comment by gliptak** [comment]
@kquick no worries, my PRs are not always accepted :) The Github build space is transforming with the arrival of Azure Pipelines and Github Actions. Please reopen if appropriate.

**Pull request closed without merging**
